make_dataset:
  masterdb_path: data/raw/masterdbFromRobMac.xlsx
  mac_path: data/raw/mcmaster-database-de-identified-comments.xlsx
  sas_path: data/raw/sask-database-de-identified-comments.xlsx
  output_path: data/interim/masterdbForNLP.xlsx

proc_spacy:
  dataset_path: ${make_dataset.output_path}
  output_path: data/interim/masterdbForNLPSpacyProc.pkl
  text_var: comment
  spacy_model: en_core_web_sm
  spacy_procs: 4
  progress_bar: True

split_train_test:
  dataset_path: ${proc_spacy.output_path}
  output_dir: data/processed
  train_path: ${split_train_test.output_dir}/train.pkl
  test_path: ${split_train_test.output_dir}/test.pkl
  test_size: 0.15
  random_state: 43
  train_file_name: train.pkl
  test_file_name: test.pkl

train:
  conda_yaml_path: './conda.yaml'
  mlflow_tracking_dir: ./mlruns
  mlflow_experiment_name: manual
  train_path: ${split_train_test.train_path}
  text_var: ${proc_spacy.text_var}_spacy
  target_var: Q2
  random_seed: 43
  punct: True
  pron: True
  stop: False
  lemma: False
  ngram_min: 1
  ngram_max: 2
  max_df: 1.0
  min_df: 1
  token_count: True
  pos_counts: False
  ent_counts: False
  vectors: False
  model_c: 0.01
  class_weight: 'balanced'

defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: random
  - override hydra/launcher: joblib

hydra:
  sweeper:
    sampler:
      seed: 43
    direction: maximize
    study_name: test_study
    storage: null
    n_trials: 100
    n_jobs: 8
    params:
      train.mlflow_experiment_name: sweep_random_100_test_yes_vectors
      train.model_c: choice(1,0.1,0.01,0.001,0.0001)
      train.punct: choice(True, False)
      train.pron: choice(True, False)
      train.stop: choice(True, False)
      train.lemma: choice(True, False)
      train.ngram_min: 1
      train.ngram_max: range(1,8)
      train.max_df: interval(0.1, 1.0)
      train.min_df: range(1,30)
      train.token_count: choice(True, False)
      train.pos_counts: choice(True, False)
      train.ent_counts: choice(True, False)
      train.vectors: choice(True, False)
      train.class_weight: balanced,null





